"""Adicionar coluna identificador na tabela concursos

Revision ID: e02026f97b2b
Revises: 367ad17e5971
Create Date: 2026-09-21 20:04:04.542916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e02026f97b2b'
down_revision: Union[str, Sequence[str], None] = '367ad17e5971'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('candidatos')
    op.drop_table('concursos')
    op.drop_table('candidaturas')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=14), nullable=False),
    sa.Column('password', sa.VARCHAR(length=200), nullable=False),
    sa.Column('role', sa.VARCHAR(length=5), nullable=False),
    sa.Column('criado_em', sa.DATETIME(), nullable=False),
    sa.Column('actualizado_em', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('candidaturas',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('criado_em', sa.DATETIME(), nullable=False),
    sa.Column('actualizado_em', sa.DATETIME(), nullable=False),
    sa.Column('id_candidato', sa.INTEGER(), nullable=False),
    sa.Column('id_concurso', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['id_candidato'], ['candidatos.id'], ),
    sa.ForeignKeyConstraint(['id_concurso'], ['concursos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('concursos',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('titulo', sa.VARCHAR(length=50), nullable=False),
    sa.Column('identificador', sa.VARCHAR(length=10), nullable=False),
    sa.Column('descricao', sa.VARCHAR(), nullable=False),
    sa.Column('numero_vagas', sa.INTEGER(), nullable=False),
    sa.Column('nota_minima', sa.FLOAT(), nullable=False),
    sa.Column('criado_em', sa.DATETIME(), nullable=False),
    sa.Column('actualizado_em', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identificador')
    )
    op.create_table('candidatos',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=50), nullable=False),
    sa.Column('bi', sa.VARCHAR(length=14), nullable=False),
    sa.Column('data_nascimento', sa.DATE(), nullable=False),
    sa.Column('media', sa.FLOAT(), nullable=False),
    sa.Column('curso', sa.VARCHAR(length=100), nullable=False),
    sa.Column('nivel_academico', sa.VARCHAR(length=12), nullable=False),
    sa.Column('criado_em', sa.DATETIME(), nullable=False),
    sa.Column('id_user', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bi')
    )
    # ### end Alembic commands ###
